### ISSUE TITLE
Update Copyright Text

### ISSUE THREAD

**Issue by adithyaakrishna** [teamlbtc/bv-website#2]
**Description:**
Write a function to display the year according to the PC or current year without having to depend on static text.

**Screenshot:**
![image](https://user-images.githubusercontent.com/23498248/139462803-222711c4-aea1-405b-970f-9402feb55e29.png)

**Comment by aayushbisen** [comment]
Can I work on this issue?

**Comment by deepthiir** [comment]
Can I work on this?

**Comment by itsmohmans** [comment]
I'm sorry I might forgot to ask to work on this, and I've already submitted a PR
