### ISSUE TITLE
Disable autofill for Footer form

### ISSUE THREAD

**Issue by uravgkarthik** [teamlbtc/bv-website#6]
Summary:
The autofill for footer form needs to be disabled

Pic:
![image](https://user-images.githubusercontent.com/33371558/139539667-7f833892-5f42-4858-a573-d2a16edf3962.png)

**Comment by deepthiir** [comment]
Can I work on this? @uravgkarthik

**Comment by uravgkarthik** [comment]
> Can I work on this? @uravgkarthik 

Sure
